### ISSUE TITLE
Cilium policies are not generating 

### ISSUE THREAD

**Issue by rohitrishim** [accuknox/discovery-engine#464] opened 2022-05-18 04:18 UTC
- When I tried to get the auto discover policies for MySQL, Elastic search deployment, cilium policies are not generating, I have tried Auto discovery on my own cluster, when I have deployed the same on office cluster I got the cilium policies

![image (4)](https://user-images.githubusercontent.com/88204255/168955789-1dd6b788-8444-44f6-96d6-00c1dda27c42.png)

- I have used same cluster configurations

**Comment by wazir-ahmed** [comment] 2022-05-18 10:43
@rohitrishim Please provide the following details.
1) Link to deployment file.
2) What is that "office cluster"? Please provide the details for the cluster.

**Comment by wazir-ahmed** [comment] 2022-05-18 16:45
Hubble relay was not enabled in the cluster where @rohitrishim facing the issue. That is the root cause. Closing this issue.

**Closed as completed by wazir-ahmed** 2022-05-18 16:45 UTC
